### ISSUE TITLE
IC3 (CC10-1212DF-E) housing not grounded

### ISSUE THREAD

**Issue by pathfinder49** [sinara-hw/Fastino#53] opened 2020-02-03 12:18 UTC
The IC3 housing is not grounded. Is this intentional? 
I'm observing a 0.6 Vp-p, ~500 kHz oscillation relative to the board ground in the IC3 housing. I found this when investigating #50.
![image](https://user-images.githubusercontent.com/14295481/73652578-242de580-467f-11ea-884f-7c627641054e.png)

**Comment by gkasprow** [comment] 2020-02-03 12:47
Try grounding and see how it influences the noise.

**Comment by hartytp** [comment] 2020-02-03 12:52
Indeed, there are an extra 4 pins missing from that pin-out.

@gkasprow was there a deliberate reason for not grounding it, or was this an oversight?

@pathfinder49 as Greg says, try to solder those pins to the ground plane and see if that changes the noise. If it makes things better we should look again at the other designs using this part.

**Comment by jordens** [comment] 2020-02-03 12:56
* Datsheet says grounding is optional (n.b. SMD version can't be grounded) and that it may improve coupled noise
* The case is isolated
* Therefore, depending on how you ground it and what's coupling to the case and how, doing so may also make the coupled noise worse

**Comment by jordens** [comment] 2020-02-03 12:58
It's also only two pins, not four.

**Comment by gkasprow** [comment] 2020-02-03 13:13
In isolated designs, the EMI level depends where you connect the shield. In our case we do not use isolation, so connect it to the input ground. The metal case may be capacitively coupled with transformer and grounding may help or make it worse.

**Comment by pathfinder49** [comment] 2020-02-03 19:06
Here Are some spectra for Ch31 with the IC3 housing grounded and floated. Overall it seems like grounding shifts spurs to higher frequencies. 

The casing was grounded with a wire from TP17 to one of the case pins.

![image](https://user-images.githubusercontent.com/14295481/73682199-cbc70a00-46b7-11ea-8f49-ca0fb8fb8b9d.png)
![image](https://user-images.githubusercontent.com/14295481/73682323-16488680-46b8-11ea-9ccb-1a0360495fe3.png)

**Comment by hartytp** [comment] 2020-02-03 19:13
> Overall it seems like grounding shifts spurs to higher frequencies. Overall spur power decreases.

Does it? From the data you posted it looks like not much has really changed there...

> The casing was grounded with a wire from TP17 to one of the case pins.

TP17 is really not the best place for this. Look at the layout...Greg has taken pains to create an "island" where as much of the SMPS current as possible flows to avoid common-impedance couplings (ground voltage changes due to the SMPS current). You're creating a pretty big antenna there.

As Greg suggested a few posts above, you really want to tie the shield to the SMPS input pin (look at the Henry Ott bible I gave you and he has a really nice section on why you always tie shields to the source ground for this kind of thing). In this case, that means connecting the screeing can to pin 3 of the SMPS.

**Comment by pathfinder49** [comment] 2020-02-04 11:14
I've measured the noise again with grounding to IC3 pin 3. I've also investigated the spur amplitude variability. There is no significant effect from the shielding.

**Comment by pathfinder49** [comment] 2020-02-04 11:22
I will investigate the if there is an effect when combined with the external power for #55.

**Comment by pathfinder49** [comment] 2020-02-04 13:28
Grounding the shield makes a large difference when eliminating 3V3MP noise. Unsurprisingly, the coupling to the output channels is channel dependent. 

With the shield floated and external power applied I get these spectra.
![image](https://user-images.githubusercontent.com/14295481/73747150-b8b34900-474e-11ea-8668-6681bc007db7.png)

Grounding the shield, the remaining spurs in ch31 dissapear. A new ~1MHz spur appears. This coincides with the N12V0A rail starting to oscillate (fix for #54 not applied)
![image](https://user-images.githubusercontent.com/14295481/73747181-ce287300-474e-11ea-8b29-ca32defdfe43.png)

Applying the #54 fix The ch31 spectrum becomes
![image](https://user-images.githubusercontent.com/14295481/73748850-2e6ce400-4752-11ea-99e1-600fcaae7cf8.png)

**Comment by hartytp** [comment] 2020-02-04 13:29
Interesting...what's the physics here? Why is the PSU housing related to the 3V3MP?

**Comment by hartytp** [comment] 2020-02-04 13:30
And, can you confirm how you grounded that?

**Comment by hartytp** [comment] 2020-02-04 13:33
Can I double check your y-axis scale. Is it really dBmV? (not dBm etc). If it's really dBmV then that spur is 20nV RMS. Is that correct?

Also, what's the worst-case output for a channel now? Is it much worse that this one? If so, this is starting to look excellent! Do you see any digital update noise, or is that all higher frequency?

**Comment by pathfinder49** [comment] 2020-02-04 13:43
> 
> 
> And, can you confirm how you grounded that?

The IC3 case was grounded from pin 3 of IC3


> 
> 
> Can I double check your y-axis scale. Is it really dBmV? (not dBm etc). If it's really dBmV then that spur is 20nV RMS. Is that correct?
> 
> Also, what's the worst-case output for a channel now? Is it much worse that this one? If so, this is starting to look excellent! Do you see any digital update noise, or is that all higher frequency?

The y axis is dBmV (over 1 Hz). The spectrum analyser is configured to give average (as oposed to peak) bin power. Therefore I expect the spur peaks to be underestimated.

**Comment by hartytp** [comment] 2020-02-04 13:46
aah, ok. Nit pick: I would label that `dBmV/Hz` which is dimensionally correct, rather than `dBmV (Hz)` which, to me, indicates that the units for `dBmV` are Hz. For spur hunting, peak power is a better unit, although, hopefully we can kill that last spur and only have noise left!

Any idea where that last one is from?

> The IC3 case was grounded from pin 3 of IC3

Well, that makes zero sense to me.

**Comment by pathfinder49** [comment] 2020-02-04 13:46
> 
> 
> Interesting...what's the physics here? Why is the PSU housing related to the 3V3MP?

Apologies, fixed.

**Comment by hartytp** [comment] 2020-02-04 13:49
AAh, you mean that this isn't 3V3MP noise, but rather than grounding the SMPS case this way significantly improves the noise. I assume your previous measurement didn't help because the case was grounded to a TP miles away.

So, we should make sure to have an issue about grounding the case that references this data. We should keep this in mind for other designs as well

**Comment by hartytp** [comment] 2020-02-04 13:50
Where is the 3V3MP noise? Or, are you running that off a separate (clean) PSU for now?

**Comment by pathfinder49** [comment] 2020-02-04 13:54
> 
> 
> Also, what's the worst-case output for a channel now? Is it much worse that this one? If so, this is starting to look excellent! Do you see any digital update noise, or is that all higher frequency?

I've checked channels 24-31 and they are all spur free aside from the single 1.2 MHz peak. I will investigate all channels once I've finished addressing #55.

**Comment by pathfinder49** [comment] 2020-02-04 13:55
> So, we should make sure to have an issue about grounding the case that references this data. We should keep this in mind for other designs as well

See title of this issue

**Comment by hartytp** [comment] 2020-02-04 14:06
I see, so this is using a separate PSU to remove the 3V3 noise.

So, just that and the final spur to find. Good work!

**Comment by hartytp** [comment] 2020-02-05 13:07
@gkasprow based on those results, I think we should consider grounding the PSU chassis to the input ground on all designs that use this part.

At the very least, let's do this via DNPd 0R resistors to make grounding later easy. But, based on this data I'd suggest we should populate those grounding resistors by default.

**Comment by jordens** [comment] 2020-02-05 14:08
Are you certain this is the correct conclusion?
Let's disentangle the observations: I see a clean spectrum above, ok. But where is the spectrum that shows that the floating shield is still a problem with the two issues you had (at least N12V0A oscillation, P3V3MP/P12V ground bounce, and measurement issues) eliminated?
I'm certainly fine with a DNP jumper, as long as it's DNP for now.

**Comment by hartytp** [comment] 2020-02-05 14:14
> Are you certain this is the correct conclusion?

Yes, but it's not clear from the above data (particularly given that some of the descriptions were incorrect).

There are three independent observations:
- N12V0A is slightly unstable, fixed by adding a capacitor. That's one spike
- Several spurs related to grounding when Fastino is connected to Kasli (more on that later). At least one fix for this is taking Kasli from the equation and powering Fastino from floating 3V3 and 12V0 lab supplies.
- Different spurs related to the PSU chassis grounding. These can be removed by grounding the SMPS shield to its input ground pin (the previous observation that the shield grounding did not help should be ignored, since the chassis was grounded to a test point on a different part of the board)

The spurs from these sources all occur at different frequencies. We've tried several different combinations of the fixes and reproducibly are able to isolate the causes/make the spurs come and go.

Based on that, I feel pretty confident that we understand this. If you (or anyone else) have time to apply the patch and check independently that's of course always appreciated.

**Comment by hartytp** [comment] 2020-02-05 14:14
Anyway, I do agree we need a summary of this with a clear description of what setups were used and what was measured. @pathfinder49 is planning to post that later on.

**Comment by jordens** [comment] 2020-02-05 14:42
Yes. Would be great to see that description and the measurement that shows the isolated difference.
I'd be happy to reproduce it.

**Comment by hartytp** [comment] 2020-02-05 14:43
Indeed. @pathfinder49 is doing a meticulous job of this, so I'll stop getting over-excited and wait for him to post results before commenting further :)

> I'd be happy to reproduce it.

Cool! Once the write-up is done, that would be useful confirmation.

**Comment by pathfinder49** [comment] 2020-02-10 13:39
[This comment](https://github.com/sinara-hw/Fastino/issues/55#issuecomment-584073610) should really have been in this issue.

The effect of grounding the sield is summarised by this plot *(explained in the linked comment).
![image](https://user-images.githubusercontent.com/14295481/74154547-c2cfbe80-4c0a-11ea-9915-6f9cbaa91f14.png)

**Closed** 2020-05-20 20:21 UTC
